PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^BookType/', include('apps.BookType.urls', namespace='BookType')),  # 图书类型模块
    url(r'^Book/', include('apps.Book.urls', namespace='Book')),  # 图书模块
    url(r'^ReaderType/', include('apps.ReaderType.urls', namespace='ReaderType')),  # 读者类型模块
    url(r'^Reader/', include('apps.Reader.urls', namespace='Reader')),  # 读者模块
    url(r'^LoanInfo/', include('apps.LoanInfo.urls', namespace='LoanInfo')),  # 借阅信息模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/BookType/urls.py
from apps.BookType.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'BookType'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<bookTypeId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<bookTypeId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<bookTypeId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<bookTypeId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/BookType/models.py
from django.db import models


class BookType(models.Model):
    bookTypeId = models.AutoField(primary_key=True, verbose_name='图书类别')
    bookTypeName = models.CharField(max_length=18, default='', verbose_name='类别名称')
    days = models.IntegerField(default=0,verbose_name='可借阅天数')

    class Meta:
        db_table = 't_BookType'
        verbose_name = '图书类型信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        bookType = {
            'bookTypeId': self.bookTypeId,
            'bookTypeName': self.bookTypeName,
            'days': self.days,
        }
        return bookType


PythonProject/apps/BookType/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.BookType.models import BookType
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台图书类型添加
    def get(self,request):

        # 使用模板
        return render(request, 'BookType/bookType_frontAdd.html')

    def post(self, request):
        bookType = BookType() # 新建一个图书类型对象然后获取参数
        bookType.bookTypeName = request.POST.get('bookType.bookTypeName')
        bookType.days = int(request.POST.get('bookType.days'))
        bookType.save() # 保存图书类型信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改图书类型
    def get(self, request, bookTypeId):
        context = {'bookTypeId': bookTypeId}
        return render(request, 'BookType/bookType_frontModify.html', context)


class FrontListView(BaseView):  # 前台图书类型查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        # 然后条件组合查询过滤
        bookTypes = BookType.objects.all()
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(bookTypes, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        bookTypes_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'bookTypes_page': bookTypes_page,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'BookType/bookType_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示图书类型详情页
    def get(self, request, bookTypeId):
        # 查询需要显示的图书类型对象
        bookType = BookType.objects.get(bookTypeId=bookTypeId)
        context = {
            'bookType': bookType
        }
        # 渲染模板显示
        return render(request, 'BookType/bookType_frontshow.html', context)


class ListAllView(View): # 前台查询所有图书类型
    def get(self,request):
        bookTypes = BookType.objects.all()
        bookTypeList = []
        for bookType in bookTypes:
            bookTypeObj = {
                'bookTypeId': bookType.bookTypeId,
                'bookTypeName': bookType.bookTypeName,
            }
            bookTypeList.append(bookTypeObj)
        return JsonResponse(bookTypeList, safe=False)


class UpdateView(BaseView):  # Ajax方式图书类型更新
    def get(self, request, bookTypeId):
        # GET方式请求查询图书类型对象并返回图书类型json格式
        bookType = BookType.objects.get(bookTypeId=bookTypeId)
        return JsonResponse(bookType.getJsonObj())

    def post(self, request, bookTypeId):
        # POST方式提交图书类型修改信息更新到数据库
        bookType = BookType.objects.get(bookTypeId=bookTypeId)
        bookType.bookTypeName = request.POST.get('bookType.bookTypeName')
        bookType.days = int(request.POST.get('bookType.days'))
        bookType.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台图书类型添加
    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'BookType/bookType_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        bookType = BookType() # 新建一个图书类型对象然后获取参数
        bookType.bookTypeName = request.POST.get('bookType.bookTypeName')
        bookType.days = int(request.POST.get('bookType.days'))
        bookType.save() # 保存图书类型信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新图书类型
    def get(self, request, bookTypeId):
        context = {'bookTypeId': bookTypeId}
        return render(request, 'BookType/bookType_modify.html', context)


class ListView(BaseView):  # 后台图书类型列表
    def get(self, request):
        # 使用模板
        return render(request, 'BookType/bookType_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        # 然后条件组合查询过滤
        bookTypes = BookType.objects.all()
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(bookTypes, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        bookTypes_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        bookTypeList = []
        for bookType in bookTypes_page:
            bookType = bookType.getJsonObj()
            bookTypeList.append(bookType)
        # 构造模板页面需要的参数
        bookType_res = {
            'rows': bookTypeList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(bookType_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除图书类型信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        bookTypeIds = self.getStrParam(request, 'bookTypeIds')
        bookTypeIds = bookTypeIds.split(',')
        count = 0
        try:
            for bookTypeId in bookTypeIds:
                BookType.objects.get(bookTypeId=bookTypeId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出图书类型信息到excel并下载
    def get(self, request):
        # 收集查询参数
        # 然后条件组合查询过滤
        bookTypes = BookType.objects.all()
        #将查询结果集转换成列表
        bookTypeList = []
        for bookType in bookTypes:
            bookType = bookType.getJsonObj()
            bookTypeList.append(bookType)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(bookTypeList)
        # 设置要导入到excel的列
        columns_map = {
            'bookTypeId': '图书类别',
            'bookTypeName': '类别名称',
            'days': '可借阅天数',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'bookTypes.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="bookTypes.xlsx"'
        return response


PythonProject/templates/BookType/bookType_add.html
{% include 'check_logstate.html' %}
{% load staticfiles %}

 <link rel="stylesheet" type="text/css" href="{% static 'css/bookType.css' %}" />
<div id="bookTypeAddDiv">
    {% csrf_token %}
	<form id="bookTypeAddForm" enctype="multipart/form-data"  method="post">
		<div>
			<span class="label">类别名称:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="bookType_bookTypeName" name="bookType.bookTypeName" style="width:200px" />

			</span>

		</div>
		<div>
			<span class="label">可借阅天数:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="bookType_days" name="bookType.days" style="width:80px" />

			</span>

		</div>
		<div class="operation">
			<a id="bookTypeAddButton" class="easyui-linkbutton">添加</a>
			<a id="bookTypeClearButton" class="easyui-linkbutton">重填</a>
		</div> 
	</form>
</div>
<script src="{% static 'js/BookType/bookType_add.js' %}"></script>

PythonProject/templates/BookType/bookType_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>图书类型添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
{% include 'header.html' %}
<div class="container">
	<div class="row">
		<div class="col-md-12 wow fadeInUp" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li role="presentation" ><a href="{% url 'BookType:frontList' %}">图书类型列表</a></li>
			    	<li role="presentation" class="active"><a href="#bookTypeAdd" aria-controls="bookTypeAdd" role="tab" data-toggle="tab">添加图书类型</a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
				    <div role="tabpanel" class="tab-pane" id="bookTypeList">
				    </div>
				    <div role="tabpanel" class="tab-pane active" id="bookTypeAdd"> 
				      	<form class="form-horizontal" name="bookTypeAddForm" id="bookTypeAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
						  <div class="form-group">
						  	 <label for="bookType_bookTypeName" class="col-md-2 text-right">类别名称:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="bookType_bookTypeName" name="bookType.bookTypeName" class="form-control" placeholder="请输入类别名称">
							 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="bookType_days" class="col-md-2 text-right">可借阅天数:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="bookType_days" name="bookType.days" class="form-control" placeholder="请输入可借阅天数">
							 </div>
						  </div>
				          <div class="form-group">
				             <span class="col-md-2""></span>
				             <span onclick="ajaxBookTypeAdd();" class="btn btn-primary bottom5 top5">添加</span>
				          </div>
						</form> 
				        <style>#bookTypeAddForm .form-group {margin:10px;}  </style>
					</div>
				</div>
			</div>
		</div>
	</div> 
</div>

{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script>
	//提交添加图书类型信息
	function ajaxBookTypeAdd() { 
		//提交之前先验证表单
		$("#bookTypeAddForm").data('bootstrapValidator').validate();
		if(!$("#bookTypeAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'BookType:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#bookTypeAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证图书类型添加表单字段
	$('#bookTypeAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"bookType.bookTypeName": {
				validators: {
					notEmpty: {
						message: "类别名称不能为空",
					}
				}
			},
			"bookType.days": {
				validators: {
					notEmpty: {
						message: "可借阅天数不能为空",
					},
					integer: {
						message: "可借阅天数不正确"
					}
				}
			},
		}
	}); 
})
</script>
</body>
</html>

PythonProject/templates/BookType/bookType_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>图书类型查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div style="display:none;">
		<div class="page-header">
    		<h1>图书类型查询</h1>
		</div>
		<form name="bookTypeQueryForm" id="bookTypeQueryForm" action="{% url 'BookType:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-12 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#bookTypeListPanel" aria-controls="bookTypeListPanel" role="tab" data-toggle="tab">图书类型列表</a></li>
			    	<li role="presentation" ><a href="{% url 'BookType:frontAdd' %}" style="display:none;">添加图书类型</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="bookTypeListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>图书类别</td><td>类别名称</td><td>可借阅天数</td><td>操作</td></tr>
                                        {% for bookType in bookTypes_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ bookType.bookTypeId }}</td>
 											<td>{{ bookType.bookTypeName }}</td>
 											<td>{{ bookType.days }}</td>
 											<td>
 												<a href="{% url 'BookType:frontShow' bookType.bookTypeId  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="bookTypeEdit('{{ bookType.bookTypeId }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="bookTypeDelete('{{ bookType.bookTypeId }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }}> 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="bookTypeEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;图书类型信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="bookTypeEditForm" id="bookTypeEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="bookType_bookTypeId_edit" class="col-md-3 text-right">图书类别:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="bookType_bookTypeId_edit" name="bookType.bookTypeId" class="form-control" placeholder="请输入图书类别" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="bookType_bookTypeName_edit" class="col-md-3 text-right">类别名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="bookType_bookTypeName_edit" name="bookType.bookTypeName" class="form-control" placeholder="请输入类别名称">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="bookType_days_edit" class="col-md-3 text-right">可借阅天数:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="bookType_days_edit" name="bookType.days" class="form-control" placeholder="请输入可借阅天数">
			 </div>
		  </div>
		</form> 
	    <style>#bookTypeEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxBookTypeModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.bookTypeQueryForm.currentPage.value = currentPage;
    document.bookTypeQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.bookTypeQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.bookTypeQueryForm.currentPage.value = pageValue;
    documentbookTypeQueryForm.submit();
}

/*弹出修改图书类型界面并初始化数据*/
function bookTypeEdit(bookTypeId) {
	$.ajax({
		url :  '/BookType/update/' + bookTypeId,
		type : "get",
		dataType: "json",
		success : function (bookType, response, status) {
			if (bookType) {
				$("#bookType_bookTypeId_edit").val(bookType.bookTypeId);
				$("#bookType_bookTypeName_edit").val(bookType.bookTypeName);
				$("#bookType_days_edit").val(bookType.days);
				$('#bookTypeEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除图书类型信息*/
function bookTypeDelete(bookTypeId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/BookType/deletes",
			data : {
				bookTypeIds : bookTypeId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#bookTypeQueryForm").submit();
					//location.href= basePath + "BookType/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交图书类型信息表单给服务器端修改*/
function ajaxBookTypeModify() {
	$.ajax({
		url :   '/BookType/update/' + $("#bookType_bookTypeId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#bookTypeEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                location.href= basePath + "BookType/frontlist";
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

})
</script>
</body>
</html>
