PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^BookType/', include('apps.BookType.urls', namespace='BookType')),  # 图书类型模块
    url(r'^Book/', include('apps.Book.urls', namespace='Book')),  # 图书模块
    url(r'^ReaderType/', include('apps.ReaderType.urls', namespace='ReaderType')),  # 读者类型模块
    url(r'^Reader/', include('apps.Reader.urls', namespace='Reader')),  # 读者模块
    url(r'^LoanInfo/', include('apps.LoanInfo.urls', namespace='LoanInfo')),  # 借阅信息模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/ReaderType/urls.py
from apps.ReaderType.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'ReaderType'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<readerTypeId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<readerTypeId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<readerTypeId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<readerTypeId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/ReaderType/models.py
from django.db import models


class ReaderType(models.Model):
    readerTypeId = models.AutoField(primary_key=True, verbose_name='读者类型编号')
    readerTypeName = models.CharField(max_length=20, default='', verbose_name='读者类型')
    number = models.IntegerField(default=0,verbose_name='可借阅数目')

    class Meta:
        db_table = 't_ReaderType'
        verbose_name = '读者类型信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        readerType = {
            'readerTypeId': self.readerTypeId,
            'readerTypeName': self.readerTypeName,
            'number': self.number,
        }
        return readerType


PythonProject/apps/ReaderType/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.ReaderType.models import ReaderType
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台读者类型添加
    def get(self,request):

        # 使用模板
        return render(request, 'ReaderType/readerType_frontAdd.html')

    def post(self, request):
        readerType = ReaderType() # 新建一个读者类型对象然后获取参数
        readerType.readerTypeName = request.POST.get('readerType.readerTypeName')
        readerType.number = int(request.POST.get('readerType.number'))
        readerType.save() # 保存读者类型信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改读者类型
    def get(self, request, readerTypeId):
        context = {'readerTypeId': readerTypeId}
        return render(request, 'ReaderType/readerType_frontModify.html', context)


class FrontListView(BaseView):  # 前台读者类型查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        # 然后条件组合查询过滤
        readerTypes = ReaderType.objects.all()
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(readerTypes, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        readerTypes_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'readerTypes_page': readerTypes_page,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'ReaderType/readerType_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示读者类型详情页
    def get(self, request, readerTypeId):
        # 查询需要显示的读者类型对象
        readerType = ReaderType.objects.get(readerTypeId=readerTypeId)
        context = {
            'readerType': readerType
        }
        # 渲染模板显示
        return render(request, 'ReaderType/readerType_frontshow.html', context)


class ListAllView(View): # 前台查询所有读者类型
    def get(self,request):
        readerTypes = ReaderType.objects.all()
        readerTypeList = []
        for readerType in readerTypes:
            readerTypeObj = {
                'readerTypeId': readerType.readerTypeId,
                'readerTypeName': readerType.readerTypeName,
            }
            readerTypeList.append(readerTypeObj)
        return JsonResponse(readerTypeList, safe=False)


class UpdateView(BaseView):  # Ajax方式读者类型更新
    def get(self, request, readerTypeId):
        # GET方式请求查询读者类型对象并返回读者类型json格式
        readerType = ReaderType.objects.get(readerTypeId=readerTypeId)
        return JsonResponse(readerType.getJsonObj())

    def post(self, request, readerTypeId):
        # POST方式提交读者类型修改信息更新到数据库
        readerType = ReaderType.objects.get(readerTypeId=readerTypeId)
        readerType.readerTypeName = request.POST.get('readerType.readerTypeName')
        readerType.number = int(request.POST.get('readerType.number'))
        readerType.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台读者类型添加
    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'ReaderType/readerType_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        readerType = ReaderType() # 新建一个读者类型对象然后获取参数
        readerType.readerTypeName = request.POST.get('readerType.readerTypeName')
        readerType.number = int(request.POST.get('readerType.number'))
        readerType.save() # 保存读者类型信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新读者类型
    def get(self, request, readerTypeId):
        context = {'readerTypeId': readerTypeId}
        return render(request, 'ReaderType/readerType_modify.html', context)


class ListView(BaseView):  # 后台读者类型列表
    def get(self, request):
        # 使用模板
        return render(request, 'ReaderType/readerType_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        # 然后条件组合查询过滤
        readerTypes = ReaderType.objects.all()
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(readerTypes, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        readerTypes_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        readerTypeList = []
        for readerType in readerTypes_page:
            readerType = readerType.getJsonObj()
            readerTypeList.append(readerType)
        # 构造模板页面需要的参数
        readerType_res = {
            'rows': readerTypeList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(readerType_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除读者类型信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        readerTypeIds = self.getStrParam(request, 'readerTypeIds')
        readerTypeIds = readerTypeIds.split(',')
        count = 0
        try:
            for readerTypeId in readerTypeIds:
                ReaderType.objects.get(readerTypeId=readerTypeId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出读者类型信息到excel并下载
    def get(self, request):
        # 收集查询参数
        # 然后条件组合查询过滤
        readerTypes = ReaderType.objects.all()
        #将查询结果集转换成列表
        readerTypeList = []
        for readerType in readerTypes:
            readerType = readerType.getJsonObj()
            readerTypeList.append(readerType)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(readerTypeList)
        # 设置要导入到excel的列
        columns_map = {
            'readerTypeId': '读者类型编号',
            'readerTypeName': '读者类型',
            'number': '可借阅数目',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'readerTypes.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="readerTypes.xlsx"'
        return response


PythonProject/templates/ReaderType/readerType_add.html
{% include 'check_logstate.html' %}
{% load staticfiles %}

 <link rel="stylesheet" type="text/css" href="{% static 'css/readerType.css' %}" />
<div id="readerTypeAddDiv">
    {% csrf_token %}
	<form id="readerTypeAddForm" enctype="multipart/form-data"  method="post">
		<div>
			<span class="label">读者类型:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="readerType_readerTypeName" name="readerType.readerTypeName" style="width:200px" />

			</span>

		</div>
		<div>
			<span class="label">可借阅数目:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="readerType_number" name="readerType.number" style="width:80px" />

			</span>

		</div>
		<div class="operation">
			<a id="readerTypeAddButton" class="easyui-linkbutton">添加</a>
			<a id="readerTypeClearButton" class="easyui-linkbutton">重填</a>
		</div> 
	</form>
</div>
<script src="{% static 'js/ReaderType/readerType_add.js' %}"></script>

PythonProject/templates/ReaderType/readerType_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>读者类型添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
{% include 'header.html' %}
<div class="container">
	<div class="row">
		<div class="col-md-12 wow fadeInUp" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li role="presentation" ><a href="{% url 'ReaderType:frontList' %}">读者类型列表</a></li>
			    	<li role="presentation" class="active"><a href="#readerTypeAdd" aria-controls="readerTypeAdd" role="tab" data-toggle="tab">添加读者类型</a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
				    <div role="tabpanel" class="tab-pane" id="readerTypeList">
				    </div>
				    <div role="tabpanel" class="tab-pane active" id="readerTypeAdd"> 
				      	<form class="form-horizontal" name="readerTypeAddForm" id="readerTypeAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
						  <div class="form-group">
						  	 <label for="readerType_readerTypeName" class="col-md-2 text-right">读者类型:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="readerType_readerTypeName" name="readerType.readerTypeName" class="form-control" placeholder="请输入读者类型">
							 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="readerType_number" class="col-md-2 text-right">可借阅数目:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="readerType_number" name="readerType.number" class="form-control" placeholder="请输入可借阅数目">
							 </div>
						  </div>
				          <div class="form-group">
				             <span class="col-md-2""></span>
				             <span onclick="ajaxReaderTypeAdd();" class="btn btn-primary bottom5 top5">添加</span>
				          </div>
						</form> 
				        <style>#readerTypeAddForm .form-group {margin:10px;}  </style>
					</div>
				</div>
			</div>
		</div>
	</div> 
</div>

{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script>
	//提交添加读者类型信息
	function ajaxReaderTypeAdd() { 
		//提交之前先验证表单
		$("#readerTypeAddForm").data('bootstrapValidator').validate();
		if(!$("#readerTypeAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'ReaderType:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#readerTypeAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证读者类型添加表单字段
	$('#readerTypeAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"readerType.readerTypeName": {
				validators: {
					notEmpty: {
						message: "读者类型不能为空",
					}
				}
			},
			"readerType.number": {
				validators: {
					notEmpty: {
						message: "可借阅数目不能为空",
					},
					integer: {
						message: "可借阅数目不正确"
					}
				}
			},
		}
	}); 
})
</script>
</body>
</html>

PythonProject/templates/ReaderType/readerType_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>读者类型查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div style="display:none;">
		<div class="page-header">
    		<h1>读者类型查询</h1>
		</div>
		<form name="readerTypeQueryForm" id="readerTypeQueryForm" action="{% url 'ReaderType:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-12 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#readerTypeListPanel" aria-controls="readerTypeListPanel" role="tab" data-toggle="tab">读者类型列表</a></li>
			    	<li role="presentation" ><a href="{% url 'ReaderType:frontAdd' %}" style="display:none;">添加读者类型</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="readerTypeListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>读者类型编号</td><td>读者类型</td><td>可借阅数目</td><td>操作</td></tr>
                                        {% for readerType in readerTypes_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ readerType.readerTypeId }}</td>
 											<td>{{ readerType.readerTypeName }}</td>
 											<td>{{ readerType.number }}</td>
 											<td>
 												<a href="{% url 'ReaderType:frontShow' readerType.readerTypeId  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="readerTypeEdit('{{ readerType.readerTypeId }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="readerTypeDelete('{{ readerType.readerTypeId }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }}> 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="readerTypeEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;读者类型信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="readerTypeEditForm" id="readerTypeEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="readerType_readerTypeId_edit" class="col-md-3 text-right">读者类型编号:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="readerType_readerTypeId_edit" name="readerType.readerTypeId" class="form-control" placeholder="请输入读者类型编号" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="readerType_readerTypeName_edit" class="col-md-3 text-right">读者类型:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="readerType_readerTypeName_edit" name="readerType.readerTypeName" class="form-control" placeholder="请输入读者类型">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="readerType_number_edit" class="col-md-3 text-right">可借阅数目:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="readerType_number_edit" name="readerType.number" class="form-control" placeholder="请输入可借阅数目">
			 </div>
		  </div>
		</form> 
	    <style>#readerTypeEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxReaderTypeModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.readerTypeQueryForm.currentPage.value = currentPage;
    document.readerTypeQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.readerTypeQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.readerTypeQueryForm.currentPage.value = pageValue;
    documentreaderTypeQueryForm.submit();
}

/*弹出修改读者类型界面并初始化数据*/
function readerTypeEdit(readerTypeId) {
	$.ajax({
		url :  '/ReaderType/update/' + readerTypeId,
		type : "get",
		dataType: "json",
		success : function (readerType, response, status) {
			if (readerType) {
				$("#readerType_readerTypeId_edit").val(readerType.readerTypeId);
				$("#readerType_readerTypeName_edit").val(readerType.readerTypeName);
				$("#readerType_number_edit").val(readerType.number);
				$('#readerTypeEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除读者类型信息*/
function readerTypeDelete(readerTypeId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/ReaderType/deletes",
			data : {
				readerTypeIds : readerTypeId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#readerTypeQueryForm").submit();
					//location.href= basePath + "ReaderType/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交读者类型信息表单给服务器端修改*/
function ajaxReaderTypeModify() {
	$.ajax({
		url :   '/ReaderType/update/' + $("#readerType_readerTypeId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#readerTypeEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                location.href= basePath + "ReaderType/frontlist";
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

})
</script>
</body>
</html>
